import { V2_CONFIG } from "../config.js";
import { GROUND_DEFAULT_PARAMS } from "../../../chunkGroundTsl.js";
import { MEADOW_DEFAULT_PARAMS } from "../../../chunkMeadowTsl.js";

function deepCloneJson(x) {
  return JSON.parse(JSON.stringify(x));
}

export function createToolState() {
  return {
    /** `view` (orbit only) | `sculpt` | `paint` | `treePaint` | `spline` | `decals` | … Defaults to `view` — matches v1. */
    mode: "view",
    /** `tile` = grid material; `tsl` = procedural TSL; `image` = tiled image-slot material. */
    terrainSurface: "tile",
    /** Texture-library slot ids picked by the surface modes that use slots. */
    textureSlots: {
      cliffSlotId: "cliff_rock",
      groundSlotId: "grass_005",
    },
    /**
     * Paint mode — 4 layers (layer 0 is base, layers 1..3 are R/G/B splat channels).
     * `activeLayer` selects what the brush paints (0 = eraser → pulls toward base).
     */
    paint: {
      activeLayer: V2_CONFIG.paint.defaultActiveLayer,
      layerSlotIds: ["ground_037", "cobblestone", "cliff_rock", "grass_005", "ground_037", "cobblestone", "cliff_rock"],
      noiseMask: 0,
      noiseScale: 3.0,
      noiseOctaves: 3,
      noiseEdgeOnly: false,
      maskPreset: "none",
      maskRotation: 0,
      maskRandomRotation: false,
      maskFollowStroke: false,
      soloLayer: -1,
      heightBlend: 0,
      heightContrast: 0.5,
    },
    groundTsl: deepCloneJson(GROUND_DEFAULT_PARAMS),
    meadowTsl: deepCloneJson(MEADOW_DEFAULT_PARAMS),
    tslGroundUi: {
      groundPresetKey: "default",
      meadowPresetKey: "default",
      meadowMix: 0.55,
      meadowSlopeMin: 0.45,
      meadowSlopeMax: 0.92,
    },
    sculptMode: "raiseLower",
    /**
     * v1 `sculptBrush` for raise/lower: `smooth` (uses brushFalloff enum) | `plateau` (mesa) | `crater` (rim-pit).
     * FBM peak / noise / terrace / ramp / erosion are separate modes via `sculptMode`.
     */
    raiseLowerStamp: V2_CONFIG.sculpt.defaultRaiseLowerStamp,
    brush: {
      radius: V2_CONFIG.sculpt.defaultRadius,
      strength: V2_CONFIG.sculpt.defaultStrength,
      falloff: V2_CONFIG.sculpt.defaultFalloff,
      /** Only affects raise/lower `smooth` stamp — v1 `PARAMS.brushFalloff`. */
      brushFalloff: V2_CONFIG.sculpt.defaultBrushFalloff,
      spacingFactor: V2_CONFIG.sculpt.spacingFactor,
      previewShape: V2_CONFIG.sculpt.previewShape,
    },
    noiseBrush: {
      noiseScale: V2_CONFIG.sculpt.noiseScale,
      noiseOctaves: V2_CONFIG.sculpt.noiseOctaves,
    },
    /**
     * Sculpt brush mask — PNG stamp that modulates stamp-mode deltas
     * (raiseLower, noise, fbmPeak, terrace). Mirror of `paint.mask*` fields but
     * independent so paint and sculpt can run different stamps simultaneously.
     */
    sculptMask: {
      preset: "none",
      rotation: 0,
      randomRotation: false,
      followStroke: false,
    },
    terrace: { ...V2_CONFIG.sculpt.terrace },
    ramp: { ...V2_CONFIG.sculpt.ramp },
    erosion: { ...V2_CONFIG.sculpt.erosion },
    fbmPeak: { ...V2_CONFIG.sculpt.fbmPeak },
    gen: { ...V2_CONFIG.sculpt.gen },
    borderMountains: { ...V2_CONFIG.borderMountains },
    terrain: {
      lodEnabled: true,
      activeRadiusInChunks: V2_CONFIG.lod.activeRadiusInChunks,
    },
    autoCliffEnabled: true,
    autoCliff: {
      slopeStart: 0.6,
      slopeEnd: 0.7,
      rockScale: 0.01,
      rockBrightness: 2.0,
      rockContrast: 1.1,
      rockTint: "#ffffff",
      rockNormalStr: 1.0,
      rockBlendSharp: 1.0,
      rockRoughMul: 1.5,
      triplanarSharp: 4.0,
    },
    light: { ...V2_CONFIG.light },
    skyMode: "physical",
    physicalSky: { ...V2_CONFIG.physicalSky },
    lensFlare: { ...V2_CONFIG.lensFlare },
    csm: { ...V2_CONFIG.csm },
    fog: {
      height: { ...V2_CONFIG.fog.height },
      distance: { ...V2_CONFIG.fog.distance },
    },
    volumetricCloud: {
      ...V2_CONFIG.volumetricCloud,
      seed: Math.random() * 1000,
    },
    volumetricCloudOptimized: {
      ...V2_CONFIG.volumetricCloudOptimized,
      seed: Math.random() * 1000,
    },
    playSmoke: {
      enabled: true,
      emitRate: 48,
      trigger: 0.04,
      opacity: 0.55,
      sizeMin: 0.55,
      sizeMax: 1.05,
      sizeGrowth: 2.6,
      lifeMin: 0.65,
      lifeMax: 1.45,
      rise: 0.75,
      spread: 0.55,
      drag: 0.12,
      color: "#6a6c76",
    },
    playCar: {
      accelScale: 1.0,
      maxSpeedScale: 1.0,
      speedometerScale: 1.0,
      cameraDistance: 10,
      cameraHeight: 3.5,
      cameraChaseSpeed: 3.5,
      cameraDriftLag: 1.8,
    },
    /**
     * Play-mode camera collision (chase cam wall pull-in + floor lift).
     * `enabled` master switch; `wallPullEnabled` and `floorClampEnabled` toggle
     * the two passes independently. `offset` = skin distance from cliff/terrain
     * surfaces. `easeOut` = exponential rate (per second) at which the wall
     * pull-in relaxes back out once the obstacle is gone.
     */
    playCamera: {
      enabled: false,
      wallPullEnabled: true,
      floorClampEnabled: true,
      offset: 0.3,
      easeOut: 5,
    },
    /** Car Howler layers (vehicle bus). Assets: `v2/static/sounds/vehicle/` */
    playCarAudio: {
      enabled: false,
      /** Overall gain on the accel engine layer */
      engineMul: 0.85,
      /** Speed (m/s) at which accel vol + pitch reach their max while W held */
      engineRefTopSpeed: 52,
      /** Volume at ref top speed when W held (× engineMul) */
      engineVolAtTop: 0.78,
      /** Howler playback rate at low / high speed while accelerating */
      enginePitchMin: 0.88,
      enginePitchMax: 1.32,
      /** Min “drive” while W from standstill so accel layer is audible immediately (0–1) */
      engineAccelThrottleFloor: 0.24,
      /** Volume rise speed when pressing W (smoothVolume ease-up) */
      engineAccelEaseUp: 22,
      /** Coast fade ease when releasing W at ~0 speed (higher = faster mute) */
      engineCoastFadeEaseLo: 2.6,
      /** Coast fade ease at ref top speed (lower = longer tail while coasting fast) */
      engineCoastFadeEaseHi: 0.4,
      /** Idle bed layer gain */
      idleMul: 1,
      idleVolRest: 0.32,
      idleVolRoll: 0.38,
      idleRefSpeed: 45,
      idlePitchMin: 0.88,
      idlePitchMax: 1.06,
      windMul: 0,
      nitroMul: 0.3,
      wheelsMul: 0,
      /** Handbrake (Space) drift / brake loop gain */
      driftBrakeMul: 0.45,
      /** Howler sprite loop window (ms). Duration 0 = loop whole file. Rebuild car audio to apply. */
      engineLoopStartMs: 0,
      engineLoopDurationMs: 0,
      idleLoopStartMs: 0,
      idleLoopDurationMs: 0,
      windLoopStartMs: 0,
      windLoopDurationMs: 0,
      wheelsLoopStartMs: 0,
      wheelsLoopDurationMs: 0,
      driftBrakeLoopStartMs: 0,
      driftBrakeLoopDurationMs: 0,
    },
    /**
     * Runtime mixer (Howler) — Unity-style buses: master × category.
     * Persisted in project JSON via terrainSerializer.
     */
    audio: {
      muteAll: false,
      pauseWhenHidden: true,
      buses: {
        master: { volume: 1, mute: false },
        sfx: { volume: 1, mute: false },
        music: { volume: 0.85, mute: false },
        voice: { volume: 1, mute: false },
        ui: { volume: 1, mute: false },
        vehicle: { volume: 1, mute: false },
      },
    },
    playSpawn: {
      enabled: true,
      x: 0,
      y: 0,
      z: 0,
      yawDeg: 0,
    },
    treePaint: {
      activeSlot: 0,
      density: 0.5,
      minSpacing: 4,
      scaleMin: 0.8,
      scaleMax: 1.2,
      randomRotation: true,
      massPlaceCount: 1000,
      massPlaceKeepExisting: true,
      slopeEnabled: true,
      slopeMax: 0.7,
    },
    treeLod: {
      lod0Distance: 120,
      lod1Distance: 300,
      fadeOutDistance: 600,
      castShadow: true,
    },
    foliageLod: {
      lod0Distance: 80,
      lod1Distance: 200,
      fadeOutDistance: 600,
    },
    foliagePaint: {
      activeSlot: 0,
      density: 0.8,
      minSpacing: 1.5,
      scaleMin: 0.7,
      scaleMax: 1.3,
      randomRotation: true,
    },
    foliageSlots: [0, 1, 2, 3, 4, 5, 6, 7].map((i) => ({
      name: `Foliage ${i + 1}`,
      enabled: true,
      textureUrl: null,
      baseScale: 1.0,
      planeCount: 3,
      planeSpread: "full",
      tilt: 0.28,
      tiltMode: "stable",
      structureSeed: 42069 + i * 1000,
      width: 1.8,
      height: 2.0,
      alphaTest: 0.5,
      roughness: 0.85,
      colorTint: "#ffffff",
      groundOcclusion: 0.7,
      normalBending: 0.6,
      sssIntensity: 1.5,
      swaySpeed: 0,
      swayStrength: 0.12,
    })),
    treeSlots: [0, 1, 2, 3, 4, 5, 6, 7].map(i => ({
      name: `Slot ${i + 1}`,
      enabled: true,
      presetFile: null,
      baseScale: 1.0,
      foliage: {
        bottomColor: "#2d5a1b",
        topColor: "#5aaa2a",
        colorVar: 0.12,
        treeColorVar: 0.15,
        alphaCutoff: 0.45,
        normalBias: 1.0,
        leafWarp: 0.28,
        aoStr: 0.70,
        sssStr: 0.0,
        sssPow: 2.0,
        sssColor: "#c8e070",
        rimStr: 0.07,
        rimPow: 2.5,
        rimColor: "#c8ffaa",
        windSpeed: 0.9,
        windStr: 0.0,
        windMicro: 0.0,
      },
    })),
    cliffs: {
      activeSlot: 0,
      sinkOffset: 2,
      transformMode: "translate",
      blendSlopeLow: 0.5,
      blendSlopeHigh: 0.85,
      blendNoiseScale: 0.06,
      blendNoiseStr: 0.15,
      blendGroundScale: 1.0,
      blendRockScale: 0.01,
      blendRockBrightness: 2.0,
      blendRockContrast: 1.1,
      blendTriplanarSharp: 4.0,
    },
    cliffSlots: [
      { name: "Cliff 1", loaded: false },
      { name: "Cliff 2", loaded: false },
      { name: "Cliff 3", loaded: false },
      { name: "Cliff 4", loaded: false },
      { name: "Cliff 5", loaded: false },
    ],
    props: {
      activeSlot: 0,
      sinkOffset: 0,
      transformMode: "translate",
      placementMode: "place",
      density: 0.5,
      minSpacing: 3,
      scaleMin: 0.8,
      scaleMax: 1.2,
      randomRotation: true,
    },
    propLod: {
      lod0Distance: 80,
      lod1Distance: 200,
      fadeOutDistance: 500,
      castShadow: true,
    },
    propSlots: [],
    barrier: {
      erase: false,
      showOverlay: true,
      overlayOpacity: 0.35,
    },
    hole: {
      erase: false,
      showOverlay: true,
      overlayOpacity: 0.35,
    },
    cave: {
      // Box-room placeholder sizes. Tuned so a default cave fits comfortably
      // under a brush radius ~8 hole and gives the player room to land + walk.
      width: 12,
      depth: 12,
      height: 6,
      opening: 4,
      ceilingOffset: 0.5,
    },
    ambientFx: {
      erase: false,
      effectType: "butterflies",
      emitterRadius: 12,
      density: 3,
      flapSpeed: 8.0,
      flapAngle: 0.8,
      glideRatio: 0.45,
      showRings: true,
      windX: 1.0,
      windZ: 0.3,
      windStrength: 1.0,
      leafSpawnHeight: 20,
      leafSize: 0.25,
      leafGravity: 0.002,
      leafTerminalVelocity: 0.02,
      leafRotationSpeed: 0.0015,
      leafAirResistance: 0.99,
      leafWindInfluence: 1.0,
      leafOpacity: 0.85,
      leafScale: 1.0,
      leafFloorOffset: 1.5,
      leafActiveType: 0,
      leafTint0: "#ff6b35",
      leafTint1: "#8B4513",
      leafTint2: "#2d7a2d",
      leafTex0: "",
      leafTex1: "",
      leafTex2: "",
    },
    fleur: {
      erase: false,
      activeSlot: 0,
      subMode: "ground",
      bloomShape: 0,
      perStroke: 20,
      minSpacing: 0.4,
      scaleMin: 0.4,
      scaleMax: 0.7,
      hoverBase: 0.45,
      hoverVariance: 0.1,
      stemBase: "#1f5c32",
      stemTop: "#6bae6e",
      stemStaticCurve: 0.1,
      interactRadius: 1.5,
      interactStrength: 0.4,
      interactGain: 0.85,
      windAmp: 0.042,
      windSpeed: 1.12,
      colorA: { preset: "main", inner: "#fff4b8", outer: "#fb8da0", glow: 0.28 },
      colorB: { preset: "sakura", inner: "#ffd9ea", outer: "#ff7ab2", glow: 0.32 },
    },
    water: {
      scale: 0.3,
      cellSpeed: 0.45,
      noiseScale: 1.52,
      noiseTimeScale: 0.6,
      distort: 0.35,
      flowZ: 0.08,
      edgeThreshold: 0.067,
      shoreColor: "#b8ecfa",
      midColor: "#7ed4f8",
      deepColor: "#3a6a8c",
      highlightColor: "#e8f8ff",
      depthRampShoreMid: 0.36,
      depthRampMidDeep: 0.72,
      opacity: 0.78,
      foamColor: "#e8f4ff",
      lineWidth: 0.5,
      glowWidth: 2.0,
      waterlineIntensity: 2.5,
      sinkOffset: -0.05,
      preset: "Small lake",
      style: "Ocean",
      transformMode: "translate",
      reflectionEnabled: true,
      reflectionScale: 0.5,
      reflectionEveryN: 2,
    },
    waterfall: {
      placeTool: "waterfall",
      splashVisible: true,
      transformMode: "translate",
      width: 4,
      totalHeight: 8,
      topLength: 2.5,
      radius: 1.2,
      segments: 128,
      flowSpeed: 0.5,
      opacity: 0.92,
      colorA: "#00544c",
      colorB: "#38d0d0",
      colorC: "#c8f0ee",
      splashRadius: 3.35,
      splashCapAngle: 0.42,
      splashYOffset: 0.0,
      splashOpacity: 0.88,
      splashNoiseScale: 2.35,
      splashFlow: 1.35,
      splashDisp: 0.62,
      splashColorA: "#f8fbff",
      splashColorB: "#a8e8f5",
    },
    road: {
      width: 40,
      segments: 400,
      heightOffset: 0,
      adaptiveLift: true,
      slopeLift: 0.35,
      liftMax: 0.6,
      closed: false,
      selectedPointY: 0,
      showHandles: true,
      activeRoadIndex: 0,
      activeStyleSectionIndex: 0,
      asphaltDark: "#252528",
      asphaltLight: "#4a4a52",
      grainScale: 14,
      grainStrength: 0.38,
      lineColor: "#f2f2f2",
      lineWidth: 0.035,
      lineSoftness: 0.003,
      lineInset: 0.055,
      edgeBlendWidth: 0.0,
      edgeBlendNoise: 8.0,
      centerLine: true,
      centerLineColor: "#f0c040",
      centerLineWidth: 0.014,
      centerLineSoftness: 0.002,
      centerLineDashed: false,
      centerLineDashScale: 0.3,
      doubleCenterLine: true,
      centerLineGap: 0.012,
      centerLeftEnabled: true,
      centerLeftColor: "#f0c040",
      centerLeftDashed: false,
      centerRightEnabled: true,
      centerRightColor: "#f0c040",
      centerRightDashed: false,
      laneLines: true,
      laneLineWidth: 0.012,
      laneDashScale: 0.05,
      colorTint: "#ffffff",
      colorBrightness: 0.5,
      enhanced: false,
      normalStrength: 1.0,
      roughnessBase: 0.55,
      reflectStrength: 0.6,
      mixBlur: 0.08,
      mixStrength: 1.5,
      mixContrast: 1.0,
      normalDistort: 0.12,
      dirtAmount: 0.35,
      dirtScale: 3.0,
      dirtContrast: 0.55,
      dirtTint: "#8f8578",
      edgeDirtBoost: 0.45,
      wearAmount: 0.28,
      wearScale: 7.5,
      wearContrast: 0.5,
      wearDarken: 0.22,
      scratchAmount: 0.18,
      scratchScale: 24.0,
      scratchThinness: 0.78,
      lineScratchAmount: 1.0,
      lineScratchScale: 5.0,
      lineScratchStretch: 1.0,
      lineScratchThreshold: 0.35,
      lineScratchSoftness: 0.15,
      lineScratchWarp: 0.4,
      lineScratchDetail: 1.0,
      lineScratchEdge: 0.3,
      roughnessDirtBoost: 0.16,
      roughnessWearReduce: 0.12,
      lodNear: 30,
      lodMid: 80,
      lodFar: 200,
      texScale: 4.0,
    },
    fullRoad: {
      width: 16,
      /** Upper cap on merged-mesh subdivisions (actual count = min(this, length × meshSegmentsPerMeter)). */
      segments: 240,
      /** Full Road merged ribbon: approximate vertex rows per meter of path arc length. */
      meshSegmentsPerMeter: 1.0,
      junctionSegments: 40,
      heightOffset: 0.05,
      adaptiveLift: true,
      slopeLift: 0.35,
      liftMax: 0.6,
      selectedPointY: 0,
      showHandles: true,
      nodeSnapRadius: 4.0,
      branchSnapRadius: 6.0,
      junctionRadius: 12.0,
      asphaltDark: "#252528",
      asphaltLight: "#4a4a52",
      grainScale: 14,
      grainStrength: 0.38,
      lineColor: "#f2f2f2",
      lineWidth: 0.03,
      lineSoftness: 0.003,
      lineInset: 0.055,
      edgeBlendWidth: 0.0,
      edgeBlendNoise: 8.0,
      centerLine: true,
      centerLineColor: "#f0c040",
      centerLineWidth: 0.012,
      centerLineSoftness: 0.002,
      centerLineDashed: true,
      centerLineDashScale: 0.08,
      doubleCenterLine: false,
      centerLineGap: 0.012,
      centerLeftEnabled: true,
      centerLeftColor: "#f0c040",
      centerLeftDashed: false,
      centerRightEnabled: true,
      centerRightColor: "#f0c040",
      centerRightDashed: false,
      laneLines: false,
      laneLineWidth: 0.01,
      laneDashScale: 0.08,
      colorTint: "#ffffff",
      colorBrightness: 0.62,
      enhanced: false,
      normalStrength: 1.0,
      roughnessBase: 0.55,
      reflectStrength: 0.45,
      mixBlur: 0.08,
      mixStrength: 1.2,
      mixContrast: 1.0,
      normalDistort: 0.12,
      dirtAmount: 0.42,
      dirtScale: 3.6,
      dirtContrast: 0.6,
      dirtTint: "#8f8578",
      edgeDirtBoost: 0.65,
      wearAmount: 0.35,
      wearScale: 8.5,
      wearContrast: 0.55,
      wearDarken: 0.26,
      scratchAmount: 0.2,
      scratchScale: 26.0,
      scratchThinness: 0.8,
      lineScratchAmount: 1.0,
      lineScratchScale: 5.0,
      lineScratchStretch: 1.0,
      lineScratchThreshold: 0.35,
      lineScratchSoftness: 0.15,
      lineScratchWarp: 0.4,
      lineScratchDetail: 1.0,
      lineScratchEdge: 0.3,
      roughnessDirtBoost: 0.2,
      roughnessWearReduce: 0.14,
      wetAmount: 0.45,
      wetCoverage: 1.0,
      puddleAmount: 0.35,
      puddleScale: 2.2,
      puddleContrast: 0.6,
      puddleEdgeBoost: 0.2,
      wetDarkening: 0.18,
      wetRoughnessMin: 0.14,
      puddleReflectStrength: 0.55,
      puddleSkySuppress: 0.9,
      puddleTint: "#5b5a58",
      lodNear: 30,
      lodMid: 80,
      lodFar: 200,
      texScale: 3.0,
      // Guardrail painting
      guardrailMode: false,
      guardrailSide: "right",
      guardrailHeight: 0.5,
      guardrailDepth: 0.2,
      guardrailThickness: 0.02,
      guardrailCrownDepth: 0.05,
      guardrailPathSegments: 80,
      guardrailPostSpacing: 2.0,
      guardrailPostWidth: 0.08,
      guardrailPostDepth: 0.06,
      guardrailPostHeight: 0.6,
      guardrailRailYOffset: 0.25,
      guardrailPostSink: 0.04,
      guardrailColor: "#9aa0a8",
      guardrailEdgeOffset: 0.3,
      // Kerb painting (racing curbs)
      kerbMode: false,
      kerbSide: "right",
      kerbWidth: 0.8,
      kerbHeight: 0.12,
      kerbLipHeight: 0.03,
      kerbEdgeOffset: 0.0,
      kerbColorA: "#cc2222",
      kerbColorB: "#f2f2f2",
      kerbStripeLength: 0.8,
      // Concrete barrier painting
      barrierMode: false,
      barrierSide: "right",
      barrierHeight: 0.85,
      barrierTopWidth: 0.15,
      barrierBottomWidth: 0.45,
      barrierEdgeOffset: 0.5,
      barrierColor: "#7d7d7d",
      // Fence painting
      fenceMode: false,
      fenceSide: "right",
      fenceHeight: 1.5,
      fencePostSpacing: 2.5,
      fencePostWidth: 0.06,
      fencePostDepth: 0.04,
      fenceRailCount: 3,
      fenceRailThickness: 0.04,
      fenceEdgeOffset: 0.5,
      fenceColor: "#5a5a5a",
      // Tunnel painting (centerline accessory)
      tunnelMode: false,
      tunnelRadius: 6,
      tunnelYOffset: 0,
      tunnelRadialSegments: 20,
      tunnelPathSegments: 160,
      tunnelColor: "#6c727a",
      // Active accessory type for painting
      accessoryType: "guardrail",
      // Road decals
      decalMode: false,
      decalType: "zebraCrossing",
      decalWidth: 4.0,
      decalLength: 3.0,
      decalColor: "#ffffff",
      decalStripeCount: 8,
      decalRotation: 0,
      decalSnapToRoad: true,
      decalTransformMode: "translate",
    },
    smartRoad: {
      width: 16,
      segments: 34,
      junctionSegments: 14,
      /** When true, Smart Road surfaces use the same diffuse/ARM/normal maps as Full Road (no reflection pass). */
      usePbrTextures: false,
      profilePreset: "flat",
      profileScale: 1.0,
      heightOffset: 0.05,
      adaptiveLift: true,
      slopeLift: 0.35,
      liftMax: 0.6,
      selectedPointY: 0,
      showHandles: true,
      lanesPerDir: 1,
      twoRoadNodes: "smooth",
      endCapStyle: "flat",
      nodeSnapRadius: 4.0,
      branchSnapRadius: 6.0,
      junctionRadius: 20.0,
      asphaltDark: "#252528",
      asphaltLight: "#4a4a52",
      grainScale: 14,
      grainStrength: 0.38,
      lineColor: "#f2f2f2",
      lineWidth: 0.03,
      lineSoftness: 0.003,
      lineInset: 0.055,
      edgeBlendWidth: 0.0,
      edgeBlendNoise: 8.0,
      centerLine: true,
      centerLineColor: "#f0c040",
      centerLineWidth: 0.012,
      centerLineSoftness: 0.002,
      centerLineDashed: true,
      centerLineDashScale: 0.08,
      doubleCenterLine: false,
      centerLineGap: 0.012,
      centerLeftEnabled: true,
      centerLeftColor: "#f0c040",
      centerLeftDashed: false,
      centerRightEnabled: true,
      centerRightColor: "#f0c040",
      centerRightDashed: false,
      laneLines: false,
      laneLineWidth: 0.01,
      laneDashScale: 0.08,
      colorTint: "#ffffff",
      colorBrightness: 0.62,
      enhanced: false,
      normalStrength: 1.0,
      roughnessBase: 0.55,
      reflectStrength: 0.45,
      mixBlur: 0.08,
      mixStrength: 1.2,
      mixContrast: 1.0,
      normalDistort: 0.12,
      dirtAmount: 0.42,
      dirtScale: 3.6,
      dirtContrast: 0.6,
      dirtTint: "#8f8578",
      edgeDirtBoost: 0.65,
      wearAmount: 0.35,
      wearScale: 8.5,
      wearContrast: 0.55,
      wearDarken: 0.26,
      scratchAmount: 0.2,
      scratchScale: 26.0,
      scratchThinness: 0.8,
      lineScratchAmount: 1.0,
      lineScratchScale: 5.0,
      lineScratchStretch: 1.0,
      lineScratchThreshold: 0.35,
      lineScratchSoftness: 0.15,
      lineScratchWarp: 0.4,
      lineScratchDetail: 1.0,
      lineScratchEdge: 0.3,
      roughnessDirtBoost: 0.2,
      roughnessWearReduce: 0.14,
      wetAmount: 0.45,
      wetCoverage: 1.0,
      puddleAmount: 0.35,
      puddleScale: 2.2,
      puddleContrast: 0.6,
      puddleEdgeBoost: 0.2,
      wetDarkening: 0.18,
      wetRoughnessMin: 0.14,
      puddleReflectStrength: 0.55,
      puddleSkySuppress: 0.9,
      puddleTint: "#5b5a58",
      lodNear: 30,
      lodMid: 80,
      lodFar: 200,
      texScale: 3.0,
      guardrailMode: false,
      guardrailSide: "right",
      guardrailHeight: 0.5,
      guardrailDepth: 0.2,
      guardrailThickness: 0.02,
      guardrailCrownDepth: 0.05,
      guardrailPathSegments: 80,
      guardrailPostSpacing: 2.0,
      guardrailPostWidth: 0.08,
      guardrailPostDepth: 0.06,
      guardrailPostHeight: 0.6,
      guardrailRailYOffset: 0.25,
      guardrailPostSink: 0.04,
      guardrailColor: "#9aa0a8",
      guardrailEdgeOffset: 0.3,
      kerbMode: false,
      kerbSide: "right",
      kerbWidth: 0.8,
      kerbHeight: 0.12,
      kerbLipHeight: 0.03,
      kerbEdgeOffset: 0.0,
      kerbColorA: "#cc2222",
      kerbColorB: "#f2f2f2",
      kerbStripeLength: 0.8,
      barrierMode: false,
      barrierSide: "right",
      barrierHeight: 0.85,
      barrierTopWidth: 0.15,
      barrierBottomWidth: 0.45,
      barrierEdgeOffset: 0.5,
      barrierColor: "#7d7d7d",
      fenceMode: false,
      fenceSide: "right",
      fenceHeight: 1.5,
      fencePostSpacing: 2.5,
      fencePostWidth: 0.06,
      fencePostDepth: 0.04,
      fenceRailCount: 3,
      fenceRailThickness: 0.04,
      fenceEdgeOffset: 0.5,
      fenceColor: "#5a5a5a",
      tunnelMode: false,
      tunnelRadius: 6,
      tunnelYOffset: 0,
      tunnelRadialSegments: 20,
      tunnelPathSegments: 160,
      tunnelColor: "#6c727a",
      accessoryType: "guardrail",
      decalMode: false,
      decalType: "zebraCrossing",
      decalWidth: 4.0,
      decalLength: 3.0,
      decalColor: "#ffffff",
      decalStripeCount: 8,
      decalRotation: 0,
      decalSnapToRoad: true,
      decalTransformMode: "translate",
    },
    river: {
      width: 8,
      segments: 240,
      heightOffset: 0.12,
      selectedPointY: 0,
      showHandles: true,
      activeRiverIndex: 0,
      closed: false,
      shaderStyle: "Basic",
      shallowColor: "#5dbfaa",
      deepColor: "#1a4a6a",
      highlightColor: "#c8ecff",
      foamColor: "#ffffff",
      foamWidth: 0.18,
      opacity: 0.88,
      flowSpeed: 0.15,
    },
    spline: {
      objectType: "trees",
      spacing: 4,
      scaleMin: 1.0,
      scaleMax: 1.0,
      alignToPath: true,
      selectedPointY: 0,
      closed: false,
      showHandles: true,
      showTrain: false,
      trainSpeed: 8,
      trainScale: 1,
      plateauHeight: 24,
      plateauFalloff: 4,
      plateauHalfWidth: 10,
      tunnelRadius: 6,
      tunnelRadialSegments: 20,
      tunnelPathSegments: 220,
      tunnelColor: "#6c727a",
      guardrailHeight: 2.3,
      guardrailThickness: 0.1,
      guardrailDepth: 1.1,
      guardrailCrownDepth: 0.3,
      guardrailPathSegments: 260,
      guardrailPostSpacing: 2.0,
      guardrailPostWidth: 0.32,
      guardrailPostDepth: 0.28,
      guardrailPostHeight: 2.8,
      guardrailRailYOffset: 1.15,
      guardrailPostSink: 0.16,
      guardrailColor: "#9aa0a8",
      guardrailFromRoadIndex: 0,
      guardrailFromRoadSide: "both",
      guardrailFromRoadEdgeOffset: 0.8,
      guardrailFromRoadStart: 0.0,
      guardrailFromRoadEnd: 1.0,
      guardrailFromRoadPostSpacingMul: 5.0,
      kerbWidth: 0.95,
      kerbHeight: 0.14,
      kerbLipHeight: 0.04,
      kerbTopInset: 0.0,
      kerbPathSegments: 260,
      kerbColorA: "#c92c2c",
      kerbColorB: "#f2f2f2",
      kerbStripeLength: 0.95,
      kerbSquareStripes: true,
      kerbStripeSharpness: 0.98,
      kerbNormalStrength: 0.45,
      kerbRoughnessMul: 1.0,
      kerbMetalness: 0.02,
      kerbTexUvScaleU: 1.0,
      kerbTexUvScaleV: 2.0,
      kerbTexUvOffsetU: 0.0,
      kerbTexUvOffsetV: 0.0,
      kerbTexBrightness: 0.06,
      kerbTexContrast: 1.08,
      kerbTexSaturation: 1.0,
      kerbFromRoadIndex: 0,
      kerbFromRoadSide: "both",
      kerbFromRoadEdgeOffset: -0.08,
      kerbFromRoadStart: 0.0,
      kerbFromRoadEnd: 1.0,
      kerbSplineSide: "right",
      kerbSplineLateralOffset: 0.0,
      activeKerbIndex: 0,
      kerbAutoApplyActive: true,
      /** Spline kerb mesh: `"strip"` = PBR ribbon; `"chunk"` = Smart Road / Full Road style blocks */
      kerbMeshStyle: "strip",
      splineWallHeight: 3.0,
      splineWallWidth: 0.22,
      splineWallPathSegs: 80,
      splineWallColor: "#7a7d82",
      splineFenceHeight: 1.45,
      splineFencePostSpacing: 2.1,
      splineFencePostWidth: 0.055,
      splineFencePostDepth: 0.038,
      splineFenceRailThick: 0.038,
      splineFenceColor: "#6a6d72",
      splineBarrierHeight: 0.8,
      splineBarrierDepth: 0.52,
      splineBarrierPathSegs: 72,
      splineBarrierColor: "#7d8075",
    },
    grass: {
      enabled: false,
      bladeHeight: 1.0,
      bladeWidth: 0.15,
      tipTaperStart: 0.5,
      bladeYSegments: 7,
      grassCount: 1516,
      fieldSize: 10,
      grassDensity: 1.0,
      windSpeed: 0.2,
      windStrength: 1.4,
      maxAngle: 1.4,
      naturalLean: 0.9,
      windAngle: 0,
      windWaveScale: 0.12,
      windGust: 0.3,
      bendFocus: 0.5,
      stiffness: 0.0,
      clumpScale: 1.5,
      clumpStrength: 0.7,
      crossed: true,
      bladeColor: "#0e300e",
      tipColor: "#004d05",
      skyBlend: 0.8,
      cylindrical: 0.3,
      viewThicken: 0.45,
      aoBase: 0.25,
      aoPower: 2.0,
      colorVariation: false,
      cvHueSpread: 0.08,
      cvSatSpread: 0.3,
      cvDryAmount: 0.15,
      cvDryColor: "#8a7a3a",
      bssIntensity: 1.2,
      bssPower: 2.0,
      bssColor: "#2d7a2d",
      frontScatter: 0.3,
      rimSSS: 0.25,
      specV1Enabled: false,
      specV1Intensity: 1.5,
      specV1Color: "#ffffff",
      specV1DirX: -1.0,
      specV1DirY: 1.0,
      specV1DirZ: 0.5,
      specV1Power: 25.6,
      specV2Enabled: false,
      specV2Intensity: 1.0,
      specV2Color: "#ffffff",
      specV2DirX: -1.0,
      specV2DirY: 0.45,
      specV2DirZ: 1.0,
      specV2NoiseScale: 3.0,
      specV2NoiseStr: 0.6,
      specV2Power: 12.0,
      specV2TipBias: 0.5,
      lodEnabled: true,
      lodMidDistance: 40,
      lodFarDistance: 80,
      lodMaxDistance: 200,
      lodFadeStart: 0.75,
      lodMidPatchSize: 18,
      lodMidSegments: 3,
      lodMidGrassCount: 1500,
      lodFarPatchSize: 28,
      lodFarSegments: 1,
      lodFarGrassCount: 1300,
      lodFarBladeWidth: 0.45,
      lodMegaMaxDistance: 400,
      lodMegaPatchSize: 60,
      lodMegaSegments: 1,
      lodMegaGrassCount: 400,
      lodMegaBladeWidth: 0.7,
      lodDebug: false,
      interactionRadius: 1.5,
      interactionStrength: 0.7,
      receiveShadow: true,
      terrainTintEnabled: false,
      terrainTintStrength: 0.5,
      terrainTintAutoSource: true,
      terrainTintManualMode: 1,
      terrainTintRootBias: 0.35,
      slopeEnabled: true,
      slopeMin: 0.65,
      slopeMax: 0.85,
    },
    /** Decals mode (D) — textured quads; instanced per texture+opacity. */
    decal: {
      opacity: 1,
      heightOffset: 0.05,
      defaultScale: 4,
      alignToNormal: true,
      conformSubdiv: 32,
      transformMode: "translate",
    },
  };
}

export function createPerfState() {
  return {
    fps: 0,
    frameMs: 0,
    lastFrameStamp: performance.now(),
    frameAccumMs: 0,
    frameCount: 0,
    activeChunks: 0,
    stream: {
      created: 0,
      remeshed: 0,
      unloaded: 0,
    },
    queues: {
      create: 0,
      remesh: 0,
      unload: 0,
    },
    trisApprox: 0,
  };
}

export function tickPerf(perf, nowMs, frameMs) {
  perf.frameMs = frameMs;
  perf.frameAccumMs += frameMs;
  perf.frameCount++;
  const elapsed = nowMs - perf.lastFrameStamp;
  if (elapsed >= 500) {
    perf.fps = (perf.frameCount * 1000) / elapsed;
    perf.frameCount = 0;
    perf.frameAccumMs = 0;
    perf.lastFrameStamp = nowMs;
  }
}

